<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-8P3UHHS" ignored="0" name="TestNG logs sample" tests="3" failures="1" timestamp="01 Sep 2017 14:10:32 GMT" time="0.045" errors="0">
  <testcase name="methodAddingNumbers" time="0.007" classname="com.testng.testlistner.LoggingClass"/>
  <testcase name="dividedByZero" time="0.001" classname="com.testng.testlistner.LoggingClass">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at com.testng.testlistner.LoggingClass.dividedByZero(LoggingClass.java:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- dividedByZero -->
  <testcase name="methodSkip" time="0.0" classname="com.testng.testlistner.LoggingClass">
    <skipped/>
  </testcase> <!-- methodSkip -->
</testsuite> <!-- TestNG logs sample -->
